version: '3.6'
services:

  #PHP Service
  psr_pramework_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: psr_pramework_api
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  nginx_psr_pramework_api:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - 8085:80/tcp
      - 485:443/tcp
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

  #MySQL Service
  db_psr_pramework_api:
    image: mysql:5.7.22
    restart: always
    tty: true
    ports:
      - 3085:3306/tcp
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default

  phpmyadmin_psr_pramework_api:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 7085:80/tcp
    links:
      - psr_pramework_api
    environment:
      PMA_HOST: ${PMA_HOST}

